---

R1:
    hostname: "192.168.178.231"
    groups:
        - cisco_group

R2:
    hostname: "192.168.178.232"
    groups:
        - cisco_group

R3:
    hostname: "192.168.178.233"
    groups:
        - cisco_group

R4:
    hostname: "192.168.178.234"
    groups:
        - cisco_group
